### ISSUE TITLE
For integer values, `MovingAverage` could use a running sum instead of full recalc

### ISSUE THREAD

**Issue by vgrudenic** [tlouwers/embedded#1]
Just a suggestion to avoid recalculating the sum in `MovingAverage<T>::GetAverage(void)`: it would make sense to have a `int64_t` sum field, and keep it updated as you insert elements, i.e. take the oldest sample from the fifo and subtract it from the sum just before adding the new sample. `GetAverage` would then just return `(double)sum/mItemsInBuffer`. 

This only works for integer sums though, due to precision loss when dealing with floats, but since this is embedded code I presume your samples are integers coming from the ADC anyway.

**Comment by tlouwers** [comment]
The initial use has been for smoothing out battery measurements, so taking integer values were used here. Since I restrict the capacity to an uint16_t anyway, keeping the 'sum' a double should work fine too. 

Thanks for the suggestion, I will see if I can improve a little here.

**Comment by tlouwers** [comment]
Made an update to use a running sum, the full recalculation is now avoided at the cost of an extra 'double' variable, which I think is very acceptable.

**Comment by tlouwers** [comment]
Update available with commit: 6c7c8d34d1715d414deb7808740cdeedf4b5693c.

Once I get the hang of how Github handles pull requests I will start using them along with a more 'git-flow'workflow.

Tnx for submitting the issue!
